practice-for-ch-rails-goal-app-long-practice-main/new-app-two/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

practice-for-ch-rails-goal-app-long-practice-main/new-app-two/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

practice-for-ch-rails-goal-app-long-practice-main/new-app-two/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

  attr_reader :password
  before_validation :ensure_session_token
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    (user && user.is_password?(password)) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private
  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

practice-for-ch-rails-goal-app-long-practice-main/new-app-two/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_logged_in
    redirect_to new_session_url if !logged_in?
  end

  def require_logged_out
    redirect_to user_url(current_user) if logged_in?
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    user = current_user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

end

practice-for-ch-rails-goal-app-long-practice-main/new-app-two/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_in, only: [:destroy]
  before_action :require_logged_out, only: [:new, :create]
  
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def destroy
    logout!
    render :new
  end
end

practice-for-ch-rails-goal-app-long-practice-main/new-app-two/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:show]
  before_action :require_logged_out, only: [:new, :create]
  
  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

practice-for-ch-rails-goal-app-long-practice-main/new-app-two/app/helpers/application_helper.rb
module ApplicationHelper
end

practice-for-ch-rails-goal-app-long-practice-main/new-app-two/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewAppTwo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
  <% if logged_in? %>
    <form action = "<%= session_url %>" method = "POST">
      <input type = "hidden" name = "_method" value = "DELETE">
      <input type = "submit" value = "Sign Out">
    </form>
  <% else %>
    <a href = "<%= new_session_url %>">Sign In</a>
    <a href = "<%= new_user_url %>">Sign Up</a>
  <% end %>
    <%= yield %>
  </body>
</html>

practice-for-ch-rails-goal-app-long-practice-main/new-app-two/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action = "<%= users_url %>" method = "POST">
  <label for = ""> Email :
    <input type = "email" name = "user[email]">
  </label>
  <br>
  <label for = ""> Password :
    <input type = "password" name = "user[password]">
  </label>
  <br>
  <input type = "submit" value = "Sign Up">
</form>

practice-for-ch-rails-goal-app-long-practice-main/new-app-two/app/views/users/show.html.erb
<h1>Welcome <%= @user.email %></h1>